import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Provix Tech",
  description: "Generated by create next app",
   icons: {
      icon: '/favicon.ico',
    },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className="cairo.variable">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-cairo bg-[#0A0E17] text-white`}
      >
        <Analytics/>
        {children}
      </body>
    </html>
    
  );
}
